### ISSUE TITLE
fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by pavelpetrovic** [PositronicsLab/Ravelin#5]
attempt to build Ravelin on Ubuntu 16.04 results in:

[ 82%] Building CXX object CMakeFiles/Ravelin.dir/src/URDFReaderd.cpp.o
In file included from /usr/include/unicode/utypes.h:38:0,
                 from /usr/include/unicode/ucnv_err.h:88,
                 from /usr/include/unicode/ucnv.h:52,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/local/Ravelin/include/Ravelin/XMLTree.h:14,
                 from /usr/local/Ravelin/src/URDFReaderd.cpp:21:
/usr/include/unicode/umachine.h:376:13: error: ‘char16_t’ does not name a type
     typedef char16_t UChar;

(and many more of these)

It seems cmake fails to configure the build switches properly.
